codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 0.55
        threshold: 5%
    patch:
      default:
        target: 0.55
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
